x-common-env: &common-env
  path: .env
  required: true

services:
  init-dataset:
    build:
      context: ../dataset
      dockerfile: ../dataset/Dockerfile
    volumes:
      - ${HOST_IMAGES_PATH}:${IMAGES_PATH}
    command: bash -c "python -m impl.coco_uploader && python -m impl.embedding_generator"
    env_file:
      - <<: *common-env
    environment:
      - IMAGES_PATH=${IMAGES_PATH}
      - FIFTYONE_DATABASE_NAME=${MONGO_DATABASE}
      - FIFTYONE_DATABASE_URI=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongodb:27017
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    links:
      - mongodb

  triton:
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    restart: always
    env_file:
      - <<: *common-env
    entrypoint: ["tritonserver", "--model-repository", "/model_repository"]
    volumes:
      - ${MODELS_PATH}:/model_repository
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    ports:
      - 8000:8000
      - 8001:8001

  mongodb:
    image: mongo:8
    restart: always
    env_file:
      - <<: *common-env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - mongo_data:/data/db

  gradio_service:
    restart: always
    build:
      context: ../dataset
      dockerfile: ../dataset/Dockerfile
    volumes:
      - ${HOST_IMAGES_PATH}:${IMAGES_PATH}
    env_file:
      - <<: *common-env
    ports:
      - 7860:7860
    environment:
      - IMAGES_PATH=${IMAGES_PATH}
      - GRADIO_SERVER_NAME=0.0.0.0
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: python -m impl.gradio_interface
    links:
      - db
    depends_on:
      - db

  db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    env_file:
      - <<: *common-env
    volumes:
      - ${PG_DATA}:/var/lib/postgresql/data
      - ./pgvector_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mongo_data: